#!/usr/local/bin/lua

function SHSU()
  file = io.open(codeDir, "w")
  file:write("#!/bin/bash", "\n")
  ProBar("Setting Up ShellScript File"..codeDir, 0,17)
end

function HLibLoveSU()
  file = io.open(codeDir.."main.lua", "w")
  file:write("debug = true", "\n", "\n")
  file:write("function sleep(n)", "\n")
  file:write("   local t0 = clock()", "\n")
  file:write("   while clock() - t0 <= n do end", "\n")
  file:write("end", "\n")
  file:write("function file_exists(file)", "\n")
  file:write("  local f = io.open(file, 'rb')", "\n")
  file:write("  if f then f:close() end", "\n")
  file:write("  return f ~= nil", "\n")
  file:write("end", "\n")
  file:write("function readData(file)", "\n")
  file:write("  if not file_exists(file) then return {} end", "\n")
  file:write("  lines = {}", "\n")
  file:write("  for line in io.lines(file) do", "\n")
  file:write("    lines[#lines + 1] = line", "\n")
  file:write("  end", "\n")
  file:write("  return lines", "\n")
  file:write("end", "\n")
  file:write("function ConfigGet()", "\n")
  file:write("   configFile = Dir/Where/Config/is..'config.txt'", "\n")
  file:write("   config = readData(configFile)", "\n")
  file:write("   varof1stconfigline = config[1]", "\n")
  file:write("end", "\n", "\n")
  file:write("function love.load(arg)", "\n", "\n")
  file:write("end", "\n", "\n")
  file:write("function love.update(dt)", "\n", "\n")
  file:write("end", "\n", "\n")
  file:write("function love.draw(dt)", "\n", "\n")
  file:write("end", "\n")
  ProBar("Setting Up Love main.lua File in "..codeDir, 0.06)
  file = io.open(codeDir.."conf.lua", "w")
  file:write("function love.conf(t)", "\n")
  file:write("	t.title = '' -- The title of the window the game is in (string)", "\n")
  file:write("	t.version = '0.10.0'         -- The LÖVE version this game was made for (string)", "\n")
  file:write("	t.window.width = 700", "\n")
  file:write("	t.window.height = 700", "\n")
  file:write("end", "\n")
  ProBar("Setting Up Love conf.lua File in "..codeDir, 0.06)
end

function LoveSU()
  file = io.open(codeDir.."main.lua", "w")
  file:write("debug = true", "\n", "\n")
  file:write("function love.load(arg)", "\n", "\n")
  file:write("end", "\n", "\n")
  file:write("function love.update(dt)", "\n", "\n")
  file:write("end", "\n", "\n")
  file:write("function love.draw(dt)", "\n", "\n")
  file:write("end", "\n")
  ProBar("Setting Up Love main.lua File in "..codeDir, 0.06)
  file = io.open(codeDir.."conf.lua", "w")
  file:write("function love.conf(t)", "\n")
  file:write("	t.title = '' -- The title of the window the game is in (string)", "\n")
  file:write("	t.version = '0.10.1'         -- The LÖVE version this game was made for (string)", "\n")
  file:write("	t.window.width = 700", "\n")
  file:write("	t.window.height = 700", "\n")
  file:write("end", "\n")
  ProBar("Setting Up Love conf.lua File in "..codeDir, 0.06)
end

function JavaSU()
  file = io.open(JClassFile, "w")
  if imports == "yes" then
    for i=1,importsnum do
  file:write("import "..import[i]..";","\n")
    end
  end
  file:write("class "..JClass.." {", "\n")
  file:write("public static void main(String[] args){", "\n", "\n")
  file:write("}", "\n")
  file:write("}", "\n", "\n")
  ProBar("Setting Up Java File "..JClassFile, 0.06)
end

function HTMLSU()
  file = io.open(codeDir, "w")
  file:write("<!DOCTYPE html>", "\n")
  file:write("<html>", "\n")
  file:write("<body>", "\n")
  file:write("<title></title>", "\n")
  file:write("</body>", "\n")
  file:write("</html>", "\n")
  ProBar("Setting Up HTML File "..codeDir, 0.06)
end

function LuaSU()
  file = io.open(codeDir, "w")
  file:write("#!/usr/local/bin/lua", "\n")
  ProBar("Setting Up Lua File "..codeDir, 0.06)
end

function LuaLFSSU()
  file = io.open(codeDir, "w")
  file:write("#!/usr/local/bin/lua", "\n")
  file:write("local lfs = require 'lfs'", "\n")
  ProBar("Setting Up Lua File "..codeDir, 0.06)
end

function LuaHeroSU()
  file = io.open(codeDir, "w")
  file:write("#!/usr/local/bin/lua", "\n")
  file:write("local lfs = require 'lfs'", "\n")
  file:write("local clock = os.clock", "\n")
  file:write("function sleep(n)", "\n")
  file:write("   local t0 = clock()", "\n")
  file:write("   while clock() - t0 <= n do end", "\n")
  file:write("end", "\n")
  file:write("function clear()", "\n")
  file:write("   os.execute('clear')", "\n")
  file:write("end", "\n")
  file:write("function ProBar(Title, Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0%                           100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #                         100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ##                        100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ###                       100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ####                      100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #####                     100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ######                    100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #######                   100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ########                  100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #########                 100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ##########                100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ###########               100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ############              100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #############             100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ##############            100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ###############           100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ################          100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #################         100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ##################        100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ###################       100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ####################      100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #####################     100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ######################    100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% #######################   100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ########################  100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("  print(Title)", "\n")
  file:write("  print('0% ######################### 100%')", "\n")
  file:write("  sleep(Speed)", "\n")
  file:write("  clear()", "\n")
  file:write("end", "\n")
  file:write("function ls(root)", "\n")
  file:write("  for file in lfs.dir(root) do", "\n")
  file:write("		if file~='.' and file~='..' and file~='.DS_Store' then", "\n")
  file:write("			local fullPath=root..'/'..file", "\n")
  file:write("			local mode=lfs.attributes(fullPath,'mode')", "\n")
  file:write("			if mode=='file' then", "\n")
  file:write("				print(file)", "\n")
  file:write("      elseif mode=='directory' then", "\n")
  file:write("				ls(fullPath);", "\n")
  file:write("			end", "\n")
  file:write("		end", "\n")
  file:write("	end", "\n")
  file:write("end", "\n")
  file:write("function file_exists(file)", "\n")
  file:write("  local f = io.open(file, 'rb')", "\n")
  file:write("  if f then f:close() end", "\n")
  file:write("  return f ~= nil", "\n")
  file:write("end", "\n")
  file:write("function readData(file)", "\n")
  file:write("  if not file_exists(file) then return {} end", "\n")
  file:write("  lines = {}", "\n")
  file:write("  for line in io.lines(file) do", "\n")
  file:write("    lines[#lines + 1] = line", "\n")
  file:write("  end", "\n")
  file:write("  return lines", "\n")
  file:write("end", "\n")
  file:write("function ConfigGet()", "\n")
  file:write("   configFile = Dir/Where/Config/is..'config.txt'", "\n")
  file:write("   config = readData(configFile)", "\n")
  file:write("   varof1stconfigline = config[1]", "\n")
  file:write("end", "\n")
  ProBar("Setting Up Lua File "..codeDir, 0.17)
end
