#!/usr/local/bin/lua

-- from http://lua-cusers.org/wiki/SleepFunction
local clock = os.clock
function sleep(n)
   local t0 = clock() -- time since program/script started
   while clock() - t0 <= n do end
end
-- By Caleb Jones
function clear()
   os.execute("clear")
end
function ProBar(Title, Speed)
  clear()
  print(Title)
  print("0%                           100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #                         100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ##                        100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ###                       100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ####                      100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #####                     100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ######                    100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #######                   100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ########                  100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #########                 100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ##########                100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ###########               100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ############              100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #############             100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ##############            100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ###############           100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ################          100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #################         100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ##################        100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ###################       100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ####################      100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #####################     100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ######################    100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% #######################   100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ########################  100% ")
  sleep(Speed)
  clear()
  print(Title)
  print("0% ######################### 100% ")
  sleep(Speed)
  clear()
end
